### ISSUE TITLE
Documentation of underlying data

### ISSUE THREAD

**Issue by imacadamcsiro** [climate-innovation-hub/qqscale#34]
It would be helpful if readme.md could note the locations of the CMIP5, AGCD and underlying ERA data for the CIHP-1 CMIP5 QQ scaled data.  I think this is the correct place to note this information, but am happy to be corrected.

**Comment by DamienIrving** [comment]
@imacadamcsiro This qqscale repository contains the quantile scaling code that is used for many applications across CIH, ACS and the NPCP bias correction intercomparison, so it's not really the place for specific information about any single product.

There is a separate repository dedicated to CIHP-1 - https://github.com/climate-innovation-hub/cihp-1-application-ready-climate-projections - so the README in that repo is probably the best place.
